### ISSUE TITLE
Triple slash when @ in git URL

### ISSUE THREAD

**Issue by jhillyerd** [samertm/homebrew-go-resources#5]
Most of my own git repos use an origin of: `https://jhillyerd@github.com/jhillyerd/repo.git`

homebrew-go-resources is munging those URLs to: `https///github.com/jhillyerd/repo.git` (note the triple slash, no colon)

I've traced it to this line of code, but I can't tell what it is supposed to do: https://github.com/samertm/homebrew-go-resources/blob/master/main.go#L157

At first I thought it was meant to handle an embedded password, but that doesn't seem to be the case, as demonstrated on this playground:

http://play.golang.org/p/E6PJDYUTBa

I'd like to submit a fix, but I don't know what special case the code is trying to handle.

**Comment by samertm** [comment]
Thank you for the bug report, and thanks for using this library :D I'd be happy to give you push access if you want to clean up the code, fix more bugs, add tests, etc. Looking back on this, I'm shocked at how I have zero tests and the code is written in an untestable manner haha. If you're interested, cleaning up the code and writing unit/integration tests would be fun.

Re: the bug report, that code was supposed to handle converting ssh paths (git@github.com:my/repo) to HTTPS (https://github.com/my/repo), but it's obvious I never tested it because it's buggy for that too.

Just broke it out into normalizeClonePath and wrote a test for it. It should work for your usecase now, too.
